name: Node.js CI/CD

env:
  SEMREL_GPG_SIGNKEY: ${{ secrets.SEMREL_GPG_SIGNKEY }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

on:
  push:
    branches:
      - main
      - development

jobs:
  build-n-test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Print git log
        run: git log --oneline -n 5

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test

  version:
    name: Update Package Version
    needs: build-n-test
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Dry run semantic release
        run: npx semantic-release --dry-run --branches development

      - name: Commit changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git diff-index --quiet HEAD || git commit -am "chore: update package version"
          git push origin development
        continue-on-error: true

  release:
    name: Release to NPM
    needs: build-n-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check package version
        id: check-version
        uses: PostHog/check-package-version@v2

      - name: Install dependencies
        if: steps.check-version.outputs.is-new-version == 'true'
        run: npm ci

      - name: Publish to NPM
        if: steps.check-version.outputs.is-new-version == 'true'
        run: npm publish
